name: Build Release Cross Platform

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: goto-bus-stop/setup-zig@v2
      - run: |
          mkdir -p bin
          rm -rf zig-cache && zig build -Dtarget=aarch64-linux-musl --summary all && cp zig-out/bin/grepe bin/grepe-linux-arm64
          rm -rf zig-cache && zig build -Dtarget=x86_64-linux-musl --summary all && cp zig-out/bin/grepe bin/grepe-linux-amd64
          rm -rf zig-cache && zig build -Dtarget=aarch64-macos-none --summary all && cp zig-out/bin/grepe bin/grepe-darwin-arm64
          rm -rf zig-cache && zig build -Dtarget=x86_64-macos-none --summary all && cp zig-out/bin/grepe bin/grepe-darwin-amd64
          rm -rf zig-cache && zig build -Dtarget=aarch64-linux-musl --summary all && cp zig-out/bin/grepe-test bin/grepe-test-linux-arm64
          rm -rf zig-cache && zig build -Dtarget=x86_64-linux-musl --summary all && cp zig-out/bin/grepe-test bin/grepe-test-linux-amd64
          rm -rf zig-cache && zig build -Dtarget=aarch64-macos-none --summary all && cp zig-out/bin/grepe-test bin/grepe-test-darwin-arm64
          rm -rf zig-cache && zig build -Dtarget=x86_64-macos-none --summary all && cp zig-out/bin/grepe-test bin/grepe-test-darwin-amd64
      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/grepe*
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
